# Generated by Django 2.1 on 2018-08-17 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('Book_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=200)),
                ('Branch', models.CharField(max_length=50)),
                ('Quantity', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_id', models.CharField(max_length=15)),
                ('Brnch', models.CharField(max_length=50)),
                ('Return_date', models.DateField()),
                ('Book_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='LMS.Books', verbose_name='Book_id')),
            ],
        ),
    ]
