# Generated by Django 2.1 on 2018-08-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='Quantity',
            field=models.IntegerField(),
        ),
    ]
