# Generated by Django 2.1 on 2018-08-27 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0003_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='Book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS.Books', verbose_name='Book_id'),
        ),
    ]
